import { createContext, useState, useContext } from 'react'

const LanguageContext = createContext()

export { LanguageContext }

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}

const translations = {
  ky: {
    // Navigation
    dashboard: 'Башкы бет',
    schedule: 'Расписание',
    profile: 'Профилим',
    notifications: 'Билдирүүлөр',
    leaveRequests: 'Өтүнмөлөр',
    reports: 'Отчеттор',
    logout: 'Чыгуу',
    markAttendance: 'Жоктоо белгилөө',
    
    // Common
    save: 'Сактоо',
    cancel: 'Жокко чыгаруу',
    delete: 'Өчүрүү',
    edit: 'Өзгөртүү',
    search: 'Издөө',
    loading: 'Жүктөлүүдө...',
    close: 'Жабуу',
    submit: 'Жөнөтүү',
    reset: 'Тазалоо',
    export: 'Экспорт',
    add: 'Кошуу',
    view: 'Көрүү',
    
    // Auth / Login
    login: 'Кирүү',
    username: 'Логин',
    password: 'Пароль',
    welcomeBack: 'Кош келиңиз!',
    signInToAccount: 'Аккаунтуңузга кириңиз',
    rememberMe: 'Эстеп калуу',
    forgotPassword: 'Паролду унуттуңузбу?',
    signingIn: 'Кирүү...',
    signIn: 'Кирүү',
    
    // Roles
    admin: 'Админ',
    manager: 'Менеджер',
    teacher: 'Мугалим',
    student: 'Студент',
    parent: 'Ата-эне',
    
    // Dashboard
    welcomeMessage: 'Кош келиңиз',
    todayStatistics: 'Бүгүнкү статистика',
    totalStudents: 'Студенттер',
    presentStudents: 'Келген',
    absentStudents: 'Келбеген',
    lateStudents: 'Кечиккен',
    recentActivity: 'Акыркы иш-аракеттер',
    viewAll: 'Баарын көрүү',
    myChildren: 'Менин балдарым',
    mySchedule: 'Менин расписанием',
    todaySchedule: 'Бүгүнкү расписание',
    noSchedule: 'Бүгүн сабактар жок',
    
    // Profile
    myProfile: 'Менин профилим',
    editProfile: 'Профилди өзгөртүү',
    firstName: 'Аты',
    lastName: 'Фамилиясы',
    email: 'Email',
    phoneNumber: 'Телефон',
    address: 'Дареги',
    emergencyContact: 'Өзгөчө кырдаалдагы байланыш',
    emergencyContactName: 'Байланыш адамы',
    emergencyContactPhone: 'Байланыш телефону',
    changePassword: 'Паролду өзгөртүү',
    changeUsername: 'Логинди өзгөртүү',
    currentPassword: 'Учурдагы пароль',
    currentUsername: 'Учурдагы логин',
    newPassword: 'Жаңы пароль',
    confirmPassword: 'Паролду ырастоо',
    newUsername: 'Жаңы логин',
    profilePhotoUpdated: 'Профиль фотосу жаңыртылды',
    security: 'Коопсуздук',
    course: 'Курс',
    subjects: 'Предметтер',
    
    // Dashboard
    totalTeachers: 'Мугалимдер',
    totalGroups: 'Группалар',
    totalSubjects: 'Предметтер',
    groupStatistics: 'Группалар боюнча статистика',
    percentage: 'Пайыз',
    progress: 'Прогресс',
    todayClasses: 'Бүгүнкү сабактар',
    markedClasses: 'Белгиленген',
    attendancePercentage: 'Катышуу пайызы',
    presentDays: 'Келген күндөр',
    absentDays: 'Келбеген күндөр',
    
    // Schedule
    scheduleTitle: 'Сабактар расписаниеси',
    selectCourse: 'Курсту тандаңыз',
    selectGroup: 'Группаны тандаңыз',
    selectLesson: 'Тандаңыз',
    addLesson: 'Жаңы сабак кошуу',
    editLesson: 'Сабакты өзгөртүү',
    deleteLesson: 'Сабакты өчүрүү',
    subject: 'Сабак',
    room: 'Кабинет',
    time: 'Убакыт',
    day: 'Күн',
    freeTime: 'Эркин убакыт',
    notSpecified: 'Белгиленген эмес',
    Monday: 'Дүйшөмбү',
    Tuesday: 'Шейшемби',
    Wednesday: 'Шаршемби',
    Thursday: 'Бейшемби',
    Friday: 'Жума',
    Saturday: 'Ишемби',
    Sunday: 'Жекшемби',
    monday: 'Дүйшөмбү',
    tuesday: 'Шейшемби',
    wednesday: 'Шаршемби',
    thursday: 'Бейшемби',
    friday: 'Жума',
    saturday: 'Ишемби',
    sunday: 'Жекшемби',
    
    // Attendance
    markAttendanceTitle: 'Катышууну белгилөө',
    todayLessons: 'Бүгүнкү сабактар',
    studentsList: 'Студенттердин тизмеси',
    present: 'Келди',
    absent: 'Келбеди',
    late: 'Кечикти',
    markAll: 'Баарын белгилөө',
    attendanceMarked: 'Катышуу белгиленди',
    attendanceSaved: 'Катышуу сакталды',
    
    // Leave Requests
    leaveRequestsTitle: 'Өтүнмөлөр',
    newRequest: 'Жаңы өтүнмө',
    startDate: 'Башталыш күнү',
    endDate: 'Аяктоо күнү',
    reason: 'Себеби',
    document: 'Документ',
    uploadDocument: 'Документ (справка)',
    pending: 'Күтүүдө',
    approved: 'Кабыл алынды',
    rejected: 'Четке кагылды',
    approve: 'Кабыл алуу',
    reject: 'Четке кагуу',
    rejectionReason: 'Четке кагуунун себеби',
    requestSubmitted: 'Өтүнмө жөнөтүлдү',
    noRequests: 'Өтүнмөлөр жок',
    downloadDocument: 'Документти жүктөп алуу',
    
    // Notifications
    notificationsTitle: 'Билдирүүлөр',
    allNotifications: 'Баары',
    unreadNotifications: 'Окулбаган',
    readNotifications: 'Окулган',
    markAllRead: 'Баарын окуу',
    noNotifications: 'Билдирүүлөр жок',
    justNow: 'Азыр эле',
    minutesAgo: 'мүнөт мурун',
    hoursAgo: 'саат мурун',
    daysAgo: 'күн мурун',
    
    // Reports
    reportsTitle: 'Катышуу отчету',
    filters: 'Чыпкалар',
    statistics: 'Статистика',
    total: 'Баары',
    presentPercent: 'Келгендер %',
    absentPercent: 'Келбегендер %',
    latePercent: 'Кечиккендер %',
    date: 'Күн',
    status: 'Статус',
    all: 'Баары',
    group: 'Топ',
    studentName: 'Студенттин аты',
    noData: 'Маалымат табылган жок',
    markedBy: 'Белгилеген',
    markedAt: 'Белгиленген убакыт',
    
    // Messages
    success: 'Ийгиликтүү!',
    error: 'Ката!',
    confirmDelete: 'Өчүрөсүзбү?',
    saved: 'Сакталды',
    deleted: 'Өчүрүлдү',
    updated: 'Жаңыртылды',
    profileUpdated: 'Профиль ийгиликтүү жаңыртылды!',
    profileUpdateError: 'Профилди жаңыртууда ката',
    passwordMismatch: 'Жаңы пароль туура эмес экенин текшериңиз!',
    passwordTooShort: 'Пароль кеминде 6 символдон турушу керек!',
    passwordChanged: 'Пароль ийгиликтүү өзгөртүлдү!',
    passwordChangeError: 'Паролду өзгөртүүдө ката',
    usernameRequired: 'Жаңы логинди жазыңыз!',
    usernameTooShort: 'Логин кеминде 3 символдон турушу керек!',
    usernameChanged: 'Логин ийгиликтүү өзгөртүлдү!',
    usernameChangeError: 'Логинди өзгөртүүдө ката'
  },
  ru: {
    // Navigation
    dashboard: 'Главная',
    schedule: 'Расписание',
    profile: 'Профиль',
    notifications: 'Уведомления',
    leaveRequests: 'Заявки',
    reports: 'Отчеты',
    logout: 'Выход',
    markAttendance: 'Отметить посещаемость',
    
    // Common
    save: 'Сохранить',
    cancel: 'Отмена',
    delete: 'Удалить',
    edit: 'Изменить',
    search: 'Поиск',
    loading: 'Загрузка...',
    close: 'Закрыть',
    submit: 'Отправить',
    reset: 'Сбросить',
    export: 'Экспорт',
    add: 'Добавить',
    view: 'Просмотр',
    
    // Auth / Login
    login: 'Войти',
    username: 'Имя пользователя',
    password: 'Пароль',
    welcomeBack: 'Добро пожаловать!',
    signInToAccount: 'Войдите в свой аккаунт',
    rememberMe: 'Запомнить меня',
    forgotPassword: 'Забыли пароль?',
    signingIn: 'Вход...',
    signIn: 'Войти',
    
    // Roles
    admin: 'Администратор',
    manager: 'Менеджер',
    teacher: 'Учитель',
    student: 'Студент',
    parent: 'Родитель',
    
    // Dashboard
    welcomeMessage: 'Добро пожаловать',
    todayStatistics: 'Статистика за сегодня',
    totalStudents: 'Студентов',
    presentStudents: 'Присутствуют',
    absentStudents: 'Отсутствуют',
    lateStudents: 'Опоздали',
    recentActivity: 'Недавняя активность',
    viewAll: 'Посмотреть все',
    myChildren: 'Мои дети',
    mySchedule: 'Мое расписание',
    todaySchedule: 'Расписание на сегодня',
    noSchedule: 'Сегодня нет занятий',
    totalTeachers: 'Учителей',
    totalGroups: 'Групп',
    totalSubjects: 'Предметов',
    groupStatistics: 'Статистика по группам',
    percentage: 'Процент',
    progress: 'Прогресс',
    todayClasses: 'Сегодняшние занятия',
    markedClasses: 'Отмечено',
    attendancePercentage: 'Процент посещаемости',
    presentDays: 'Дней присутствовал',
    absentDays: 'Дней отсутствовал',
    
    // Profile
    myProfile: 'Мой профиль',
    editProfile: 'Редактировать профиль',
    firstName: 'Имя',
    lastName: 'Фамилия',
    email: 'Email',
    phoneNumber: 'Телефон',
    address: 'Адрес',
    emergencyContact: 'Экстренный контакт',
    emergencyContactName: 'Имя контакта',
    emergencyContactPhone: 'Телефон контакта',
    changePassword: 'Изменить пароль',
    changeUsername: 'Изменить логин',
    currentPassword: 'Текущий пароль',
    currentUsername: 'Текущий логин',
    newPassword: 'Новый пароль',
    confirmPassword: 'Подтвердите пароль',
    newUsername: 'Новый логин',
    profilePhotoUpdated: 'Фото профиля обновлено',
    security: 'Безопасность',
    course: 'Курс',
    subjects: 'Предметы',
    
    // Schedule
    scheduleTitle: 'Расписание занятий',
    selectCourse: 'Выберите курс',
    selectGroup: 'Выберите группу',
    selectLesson: 'Выберите',
    addLesson: 'Добавить занятие',
    editLesson: 'Редактировать занятие',
    deleteLesson: 'Удалить занятие',
    subject: 'Предмет',
    room: 'Кабинет',
    time: 'Время',
    day: 'День',
    freeTime: 'Свободное время',
    notSpecified: 'Не указано',
    Monday: 'Понедельник',
    Tuesday: 'Вторник',
    Wednesday: 'Среда',
    Thursday: 'Четверг',
    Friday: 'Пятница',
    Saturday: 'Суббота',
    Sunday: 'Воскресенье',
    monday: 'Понедельник',
    tuesday: 'Вторник',
    wednesday: 'Среда',
    thursday: 'Четверг',
    friday: 'Пятница',
    saturday: 'Суббота',
    sunday: 'Воскресенье',
    
    // Attendance
    markAttendanceTitle: 'Отметить посещаемость',
    todayLessons: 'Сегодняшние занятия',
    studentsList: 'Список студентов',
    present: 'Присутствовал',
    absent: 'Отсутствовал',
    late: 'Опоздал',
    markAll: 'Отметить всех',
    attendanceMarked: 'Посещаемость отмечена',
    attendanceSaved: 'Посещаемость сохранена',
    
    // Leave Requests
    leaveRequestsTitle: 'Заявки на отсутствие',
    newRequest: 'Новая заявка',
    startDate: 'Дата начала',
    endDate: 'Дата окончания',
    reason: 'Причина',
    document: 'Документ',
    uploadDocument: 'Документ (справка)',
    pending: 'Ожидание',
    approved: 'Одобрено',
    rejected: 'Отклонено',
    approve: 'Одобрить',
    reject: 'Отклонить',
    rejectionReason: 'Причина отклонения',
    requestSubmitted: 'Заявка отправлена',
    noRequests: 'Нет заявок',
    downloadDocument: 'Скачать документ',
    
    // Notifications
    notificationsTitle: 'Уведомления',
    allNotifications: 'Все',
    unreadNotifications: 'Непрочитанные',
    readNotifications: 'Прочитанные',
    markAllRead: 'Отметить все как прочитанные',
    noNotifications: 'Нет уведомлений',
    justNow: 'Только что',
    minutesAgo: 'минут назад',
    hoursAgo: 'часов назад',
    daysAgo: 'дней назад',
    
    // Reports
    reportsTitle: 'Отчет о посещаемости',
    filters: 'Фильтры',
    statistics: 'Статистика',
    total: 'Всего',
    presentPercent: 'Присутствовали %',
    absentPercent: 'Отсутствовали %',
    latePercent: 'Опоздали %',
    date: 'Дата',
    status: 'Статус',
    all: 'Все',
    group: 'Группа',
    studentName: 'Имя студента',
    noData: 'Данные не найдены',
    markedBy: 'Отметил',
    markedAt: 'Время отметки',
    
    // Messages
    success: 'Успешно!',
    error: 'Ошибка!',
    confirmDelete: 'Удалить?',
    saved: 'Сохранено',
    deleted: 'Удалено',
    updated: 'Обновлено',
    profileUpdated: 'Профиль успешно обновлен!',
    profileUpdateError: 'Ошибка при обновлении профиля',
    passwordMismatch: 'Новый пароль не совпадает!',
    passwordTooShort: 'Пароль должен содержать минимум 6 символов!',
    passwordChanged: 'Пароль успешно изменен!',
    passwordChangeError: 'Ошибка при изменении пароля',
    usernameRequired: 'Введите новый логин!',
    usernameTooShort: 'Логин должен содержать минимум 3 символа!',
    usernameChanged: 'Логин успешно изменен!',
    usernameChangeError: 'Ошибка при изменении логина'
  },
  en: {
    // Navigation
    dashboard: 'Dashboard',
    schedule: 'Schedule',
    profile: 'Profile',
    notifications: 'Notifications',
    leaveRequests: 'Leave Requests',
    reports: 'Reports',
    logout: 'Logout',
    markAttendance: 'Mark Attendance',
    
    // Common
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
    loading: 'Loading...',
    close: 'Close',
    submit: 'Submit',
    reset: 'Reset',
    export: 'Export',
    add: 'Add',
    view: 'View',
    
    // Auth / Login
    login: 'Login',
    username: 'Username',
    password: 'Password',
    welcomeBack: 'Welcome Back!',
    signInToAccount: 'Please sign in to your account',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    signingIn: 'Signing in...',
    signIn: 'Sign In',
    
    // Roles
    admin: 'Administrator',
    manager: 'Manager',
    teacher: 'Teacher',
    student: 'Student',
    parent: 'Parent',
    
    // Dashboard
    welcomeMessage: 'Welcome',
    todayStatistics: "Today's Statistics",
    totalStudents: 'Total Students',
    presentStudents: 'Present',
    absentStudents: 'Absent',
    lateStudents: 'Late',
    recentActivity: 'Recent Activity',
    viewAll: 'View All',
    myChildren: 'My Children',
    mySchedule: 'My Schedule',
    todaySchedule: "Today's Schedule",
    noSchedule: 'No classes today',
    totalTeachers: 'Total Teachers',
    totalGroups: 'Total Groups',
    totalSubjects: 'Total Subjects',
    groupStatistics: 'Group Statistics',
    percentage: 'Percentage',
    progress: 'Progress',
    todayClasses: "Today's Classes",
    markedClasses: 'Marked',
    attendancePercentage: 'Attendance Percentage',
    presentDays: 'Present Days',
    absentDays: 'Absent Days',
    
    // Profile
    myProfile: 'My Profile',
    editProfile: 'Edit Profile',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    phoneNumber: 'Phone Number',
    address: 'Address',
    emergencyContact: 'Emergency Contact',
    emergencyContactName: 'Contact Name',
    emergencyContactPhone: 'Contact Phone',
    changePassword: 'Change Password',
    changeUsername: 'Change Username',
    currentPassword: 'Current Password',
    currentUsername: 'Current Username',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    newUsername: 'New Username',
    profilePhotoUpdated: 'Profile photo updated',
    security: 'Security',
    course: 'Course',
    subjects: 'Subjects',
    
    // Schedule
    scheduleTitle: 'Class Schedule',
    selectCourse: 'Select Course',
    selectGroup: 'Select Group',
    selectLesson: 'Select',
    addLesson: 'Add Lesson',
    editLesson: 'Edit Lesson',
    deleteLesson: 'Delete Lesson',
    subject: 'Subject',
    room: 'Room',
    time: 'Time',
    day: 'Day',
    freeTime: 'Free Time',
    notSpecified: 'Not Specified',
    Monday: 'Monday',
    Tuesday: 'Tuesday',
    Wednesday: 'Wednesday',
    Thursday: 'Thursday',
    Friday: 'Friday',
    Saturday: 'Saturday',
    Sunday: 'Sunday',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    
    // Attendance
    markAttendanceTitle: 'Mark Attendance',
    todayLessons: "Today's Lessons",
    studentsList: 'Students List',
    present: 'Present',
    absent: 'Absent',
    late: 'Late',
    markAll: 'Mark All',
    attendanceMarked: 'Attendance Marked',
    attendanceSaved: 'Attendance Saved',
    
    // Leave Requests
    leaveRequestsTitle: 'Leave Requests',
    newRequest: 'New Request',
    startDate: 'Start Date',
    endDate: 'End Date',
    reason: 'Reason',
    document: 'Document',
    uploadDocument: 'Upload Document',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    approve: 'Approve',
    reject: 'Reject',
    rejectionReason: 'Rejection Reason',
    requestSubmitted: 'Request Submitted',
    noRequests: 'No Requests',
    downloadDocument: 'Download Document',
    
    // Notifications
    notificationsTitle: 'Notifications',
    allNotifications: 'All',
    unreadNotifications: 'Unread',
    readNotifications: 'Read',
    markAllRead: 'Mark All as Read',
    noNotifications: 'No Notifications',
    justNow: 'Just now',
    minutesAgo: 'minutes ago',
    hoursAgo: 'hours ago',
    daysAgo: 'days ago',
    
    // Reports
    reportsTitle: 'Attendance Reports',
    filters: 'Filters',
    statistics: 'Statistics',
    total: 'Total',
    presentPercent: 'Present %',
    absentPercent: 'Absent %',
    latePercent: 'Late %',
    date: 'Date',
    status: 'Status',
    all: 'All',
    group: 'Group',
    studentName: 'Student Name',
    noData: 'No data found',
    markedBy: 'Marked By',
    markedAt: 'Marked At',
    
    // Messages
    success: 'Success!',
    error: 'Error!',
    confirmDelete: 'Delete?',
    saved: 'Saved',
    deleted: 'Deleted',
    updated: 'Updated',
    profileUpdated: 'Profile successfully updated!',
    profileUpdateError: 'Error updating profile',
    passwordMismatch: 'New password does not match!',
    passwordTooShort: 'Password must be at least 6 characters!',
    passwordChanged: 'Password successfully changed!',
    passwordChangeError: 'Error changing password',
    usernameRequired: 'Please enter a new username!',
    usernameTooShort: 'Username must be at least 3 characters!',
    usernameChanged: 'Username successfully changed!',
    usernameChangeError: 'Error changing username'
  }
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(
    localStorage.getItem('language') || 'ky'
  )

  const changeLanguage = (lang) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key) => {
    return translations[language][key] || key
  }

  const value = {
    language,
    changeLanguage,
    t
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}
