# Generated by Django 4.2.7 on 2025-10-22 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.schedule'),
        ),
    ]
