# Generated by Django 4.2.7 on 2025-10-24 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_attendance_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активдүү'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Студенттин аты'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сабактын аты'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject'),
        ),
    ]
