# Generated by Django 4.2.7 on 2025-11-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_attendance_is_active_attendance_student_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="day",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                ],
                max_length=10,
                verbose_name="Күн",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADMIN", "Админ"),
                    ("MANAGER", "Менеджер"),
                    ("TEACHER", "Мугалим"),
                    ("STUDENT", "Студент"),
                    ("PARENT", "Ата-энелер"),
                ],
                max_length=20,
                null=True,
                verbose_name="Роль",
            ),
        ),
    ]
