# Generated by Django 4.2.7 on 2025-11-15 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_schedule_day_alter_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="time_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.timeslot",
                verbose_name="Убакыт периоду",
            ),
        ),
    ]
