# Generated by Django 4.2.7 on 2025-12-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_attendance_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='students',
        ),
    ]
